In [1]:
import torch

Here, I am creating basic Tensors

In [2]:
#Here, I am getting float32 as the datatype as it is the default datatype for PyTorch tensors.
d = torch.zeros((5, 5))
print(d)
print(d.dtype)
print(d.device)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
torch.float32
cpu


In [3]:
#Here, I am changing the datatype to int32 and the device to GPU if available.
d = torch.zeros((5, 5), dtype=torch.int32, device='cuda' if torch.cuda.is_available() else 'cpu')
print(d)

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)


In [4]:
a = torch.ones((5, 5), dtype=torch.int16)
print(a)
print(a.dtype)
print(a.device)

tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int16)
torch.int16
cpu


Here, I am generating random numbers with the help of seed also, generating same number with the help of seed() as it set the starting point of numbers and then sequence follow.

In [5]:
torch.manual_seed(42)
r1 = torch.rand((2,2))
print(r1)

r2 = torch.rand((2, 2))
print('Different random numbers:\n', r2)

torch.manual_seed(42)
r3 = torch.rand((2, 2))
print('Same random numbers as r1:\n', r3)    



tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])
Different random numbers:
 tensor([[0.3904, 0.6009],
        [0.2566, 0.7936]])
Same random numbers as r1:
 tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])


Here, I am doing arithmcatic opeartions on tensors.

In [6]:
ones = torch.ones((2, 3))

twos = ones * 2 # here it multiplies each element in the tensor by 2

threes = ones + twos # here it adds ones and twos to each element in the tensor
print(threes)
print(threes.dtype)
print(threes.shape)

tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.float32
torch.Size([2, 3])


In [7]:
# Here you can not add tensors of different shapes, so the following line will raise an error.
r1 = torch.rand((2, 3))
r2 = torch.rand((3, 2))

print(r1 + r2) # element-wise addition

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [ ]:
# Example of mathematical opeartions available in Pytorch

# a random metrix of shape (2, 2) with values between -1 and 1
m1 = (torch.rand(2,2)-0.5) * 2
print(m1)

# absolute value
print(torch.abs(m1))

# trignometric functions
print(torch.asin(m1))

# 

tensor([[ 0.2687, -0.2712],
        [ 0.4209,  0.8928]])
tensor([[0.2687, 0.2712],
        [0.4209, 0.8928]])
tensor([[ 0.2720, -0.2746],
        [ 0.4344,  1.1036]])
